# Generated by Django 4.1.3 on 2022-12-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tabla_test_delete_db_moochi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_moochi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=101)),
                ('apellido', models.CharField(max_length=101)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=10)),
                ('password2', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Tabla_test',
        ),
    ]
